# Generated by Django 4.2.7 on 2023-12-29 14:20

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOSCFormAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormEducationalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormFoodDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_distribution', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormMealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18)),
                ('organization_site', models.CharField(max_length=255, null=True)),
                ('social_midia', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('priority_category', models.CharField(choices=[('ILP', 'Instituição de Longa Permanência'), ('IOAS', 'Instituição de Organização e Apoio Social'), ('UDM', 'Unidade de Distribuição / Mediadora')], max_length=4)),
                ('activities_detail', models.CharField(max_length=500)),
                ('quantity_workers', models.IntegerField()),
                ('quantity_volunteers', models.IntegerField()),
                ('quantity_people_served_monthly', models.IntegerField()),
                ('has_adequate_space', models.BooleanField()),
                ('has_freezing_system', models.BooleanField()),
                ('has_local_kitchen', models.BooleanField()),
                ('has_refectory', models.BooleanField()),
                ('serve_local_meals', models.BooleanField()),
                ('has_nutritionist', models.BooleanField()),
                ('disponibility_collection', models.CharField(choices=[('ONEX', '1 vez por semana'), ('TWOX', '2 vezes por semana'), ('THREEX', '3 vezes por semana'), ('FOURX', '4 vezes por semana'), ('FIVEX', '5 vezes por semana'), ('SIXX', '6 vezes por semana'), ('ALLX', 'Todos os dias')], default='ONEX', max_length=6)),
                ('collection_restriction_detail', models.CharField(max_length=500, null=True)),
                ('donation_destination', models.CharField(max_length=500, null=True)),
                ('has_public_agreement', models.BooleanField()),
                ('has_specific_agreement', models.BooleanField()),
                ('has_updated_cnpj', models.BooleanField()),
                ('has_updated_member_registration', models.BooleanField()),
                ('has_updated_minute_inauguration_assembly', models.BooleanField()),
                ('has_updated_health_permit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormOtherPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.newoscformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormOtherPartnerFrequencyReceved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormTargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('form_answer', models.ManyToManyField(related_name='target_audience', to='forms.newoscformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormResponsableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('form_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='forms.newoscformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormRecessMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form_answer', models.ManyToManyField(related_name='recess_months', to='forms.newoscformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormOtherPartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('food_distribution', models.ManyToManyField(related_name='partner_type', to='forms.newoscformotherpartner')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormOtherPartnerFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('food_distribution', models.ManyToManyField(related_name='food_type', to='forms.newoscformotherpartner')),
            ],
        ),
        migrations.AddField(
            model_name='newoscformotherpartner',
            name='frequency_receved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.newoscformotherpartnerfrequencyreceved'),
        ),
        migrations.CreateModel(
            name='NewOSCFormMealTypeMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_serves', models.IntegerField(blank=True, null=True)),
                ('people_server_daily', models.IntegerField(blank=True, null=True)),
                ('form_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.newoscformmodel')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_types_mm', to='forms.newoscformmealtype')),
            ],
        ),
        migrations.AddField(
            model_name='newoscformmealtype',
            name='form_answer',
            field=models.ManyToManyField(related_name='meal_types', through='forms.NewOSCFormMealTypeMM', to='forms.newoscformmodel'),
        ),
        migrations.CreateModel(
            name='NewOSCFormFoodDistributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('food_distribution', models.ManyToManyField(related_name='distribution_type', to='forms.newoscformfooddistribution')),
            ],
        ),
        migrations.AddField(
            model_name='newoscformfooddistribution',
            name='form_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution', to='forms.newoscformmodel'),
        ),
        migrations.CreateModel(
            name='NewOSCFormEducationalUsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('food_distribution', models.ManyToManyField(related_name='educational_usage_type', to='forms.newoscformeducationalusage')),
            ],
        ),
        migrations.AddField(
            model_name='newoscformeducationalusage',
            name='form_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_usage', to='forms.newoscformmodel'),
        ),
        migrations.CreateModel(
            name='NewOSCFormDonationExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transport', models.CharField(max_length=500)),
                ('vehicle_description', models.CharField(max_length=500)),
                ('form_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_extraction', to='forms.newoscformmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewOSCFormAgeGroupMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_people_served_monthly', models.IntegerField(blank=True, null=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_group_mm', to='forms.newoscformagegroup')),
                ('form_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_group_mm', to='forms.newoscformmodel')),
            ],
        ),
        migrations.AddField(
            model_name='newoscformagegroup',
            name='form_answer',
            field=models.ManyToManyField(related_name='age_group', through='forms.NewOSCFormAgeGroupMM', to='forms.newoscformmodel'),
        ),
    ]
