# Generated by Django 4.2.7 on 2023-12-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_newoscformagegroupmm_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformagegroupmm',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_group_mm', to='forms.newoscformagegroup'),
        ),
        migrations.AlterField(
            model_name='newoscformfooddistribution',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformmealtypemm',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_types_mm', to='forms.newoscformmodel'),
        ),
    ]
