# Generated by Django 4.2.7 on 2024-01-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_newoscformagegroupmm_age_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newoscformeducationalusagetype',
            old_name='food_distribution',
            new_name='educational_usage',
        ),
        migrations.AlterField(
            model_name='newoscformdonationextraction',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_extraction', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformeducationalusage',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_usage', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformotherpartner',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.newoscformmodel'),
        ),
    ]
