# Generated by Django 4.2.7 on 2024-01-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_food_distribution_newoscformeducationalusagetype_educational_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformeducationalusage',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_usage', to='forms.newoscformmodel'),
        ),
    ]
