# Generated by Django 4.2.7 on 2024-01-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_newoscformeducationalusage_form_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformdonationextraction',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_extraction', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformotherpartner',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.newoscformmodel'),
        ),
    ]
