# Generated by Django 4.2.7 on 2024-01-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_newoscformdonationextraction_form_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformotherpartner',
            name='frequency_receved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.newoscformotherpartnerfrequencyreceved'),
        ),
    ]
