# Generated by Django 4.2.7 on 2024-01-06 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_newoscformotherpartner_frequency_receved'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoscformmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
