# Generated by Django 4.2.7 on 2024-02-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_newoscformmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOSCFormDonationExtractionTransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='organization_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='social_midia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newoscformdonationextraction',
            name='type_of_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_type', to='forms.newoscformdonationextractiontransporttype'),
        ),
    ]
