# Generated by Django 4.2.7 on 2024-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_newoscformdonationextractiontransporttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoscformmodel',
            name='people_benefited',
            field=models.IntegerField(default=False),
        ),
    ]
