# Generated by Django 4.2.7 on 2024-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_newoscformmodel_people_benefited'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoscformmodel',
            name='has_registration_form',
            field=models.BooleanField(default=False),
        ),
    ]
