# Generated by Django 4.2.7 on 2024-04-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_newoscformmodel_has_registration_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newoscformfooddistribution',
            name='form_answer',
        ),
        migrations.RemoveField(
            model_name='newoscformfooddistributiontype',
            name='food_distribution',
        ),
        migrations.AddField(
            model_name='newoscformfooddistribution',
            name='distribution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution', to='forms.newoscformfooddistributiontype'),
        ),
        migrations.AddField(
            model_name='newoscformfooddistribution',
            name='form_answer_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution', to='forms.newoscformmodel'),
        ),
        migrations.AddField(
            model_name='newoscformfooddistributiontype',
            name='form_answer',
            field=models.ManyToManyField(related_name='distribution_type', through='forms.NewOSCFormFoodDistribution', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='collection_restriction_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='donation_destination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
