# Generated by Django 4.2.7 on 2024-04-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_remove_newoscformfooddistribution_form_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newoscformfooddistribution',
            old_name='form_answer_key',
            new_name='form_answer',
        ),
    ]
