# Generated by Django 4.2.7 on 2024-04-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_rename_form_answer_key_newoscformfooddistribution_form_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformfooddistribution',
            name='distribution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution_mm', to='forms.newoscformfooddistributiontype'),
        ),
        migrations.AlterField(
            model_name='newoscformfooddistribution',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution_mm', to='forms.newoscformmodel'),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
