# Generated by Django 4.2.7 on 2024-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_newoscformfooddistribution_distribution_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newoscformeducationalusage',
            name='usage_details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='activities_detail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='collection_restriction_detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newoscformmodel',
            name='donation_destination',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
