# Generated by Django 4.2.7 on 2024-10-03 09:56

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_newoscformeducationalusage_usage_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSaveNewOSCFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18)),
                ('organization_site', models.CharField(blank=True, max_length=255, null=True)),
                ('social_midia', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('priority_category', models.CharField(choices=[('ILP', 'Instituição de Longa Permanência'), ('IOAS', 'Instituição de Organização e Apoio Social'), ('UDM', 'Unidade de Distribuição / Mediadora')], max_length=4)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormResponsableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('pre_save', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='forms.presavenewoscformmodel')),
            ],
        ),
    ]
