# Generated by Django 4.2.7 on 2024-10-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_presavenewoscformmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoscformmodel',
            name='pre_save',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_answer', to='forms.presavenewoscformmodel'),
        ),
    ]
