# Generated by Django 4.2.7 on 2025-01-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_newoscformmodel_pre_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSaveNewOSCFormAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormDonationExtractionTransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormEducationalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_details', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormFoodDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_distribution', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormMealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormOtherPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormOtherPartnerFrequencyReceved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='activities_detail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='collection_restriction_detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='disponibility_collection',
            field=models.CharField(choices=[('ONEX', '1 vez por semana'), ('TWOX', '2 vezes por semana'), ('THREEX', '3 vezes por semana'), ('FOURX', '4 vezes por semana'), ('FIVEX', '5 vezes por semana'), ('SIXX', '6 vezes por semana'), ('ALLX', 'Todos os dias')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='donation_destination',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_adequate_space',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_freezing_system',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_local_kitchen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_nutritionist',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_public_agreement',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_refectory',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_registration_form',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_specific_agreement',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_updated_cnpj',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_updated_health_permit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_updated_member_registration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='has_updated_minute_inauguration_assembly',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='people_benefited',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='quantity_people_served_monthly',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='quantity_volunteers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='quantity_workers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='presavenewoscformmodel',
            name='serve_local_meals',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='presavenewoscformmodel',
            name='priority_category',
            field=models.CharField(choices=[('ILP', 'Instituição de Longa Permanência'), ('IOAS', 'Instituição de Organização e Apoio Social'), ('UDM', 'Unidade de Distribuição / Mediadora')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='presavenewoscformresponsablemodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presavenewoscformresponsablemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presavenewoscformresponsablemodel',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presavenewoscformresponsablemodel',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormTargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('default', models.BooleanField(default=False)),
                ('form_answer', models.ManyToManyField(related_name='target_audience', to='forms.presavenewoscformmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormRecessMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('form_answer', models.ManyToManyField(related_name='recess_months', to='forms.presavenewoscformmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormOtherPartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('food_distribution', models.ManyToManyField(related_name='partner_type', to='forms.presavenewoscformotherpartner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormOtherPartnerFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('food_distribution', models.ManyToManyField(related_name='food_type', to='forms.presavenewoscformotherpartner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformotherpartner',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.presavenewoscformmodel'),
        ),
        migrations.AddField(
            model_name='presavenewoscformotherpartner',
            name='frequency_receved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_parters', to='forms.presavenewoscformotherpartnerfrequencyreceved'),
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormMealTypeMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_serves', models.IntegerField(blank=True, null=True)),
                ('people_server_daily', models.IntegerField(blank=True, null=True)),
                ('form_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_types_mm', to='forms.presavenewoscformmodel')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_types_mm', to='forms.presavenewoscformmealtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformmealtype',
            name='form_answer',
            field=models.ManyToManyField(related_name='meal_types', through='forms.PreSaveNewOSCFormMealTypeMM', to='forms.presavenewoscformmodel'),
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormFoodDistributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('form_answer', models.ManyToManyField(related_name='distribution_type', through='forms.PreSaveNewOSCFormFoodDistribution', to='forms.presavenewoscformmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformfooddistribution',
            name='distribution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution_mm', to='forms.presavenewoscformfooddistributiontype'),
        ),
        migrations.AddField(
            model_name='presavenewoscformfooddistribution',
            name='form_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_distribution_mm', to='forms.presavenewoscformmodel'),
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormEducationalUsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('educational_usage', models.ManyToManyField(related_name='educational_usage_type', to='forms.presavenewoscformeducationalusage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformeducationalusage',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_usage', to='forms.presavenewoscformmodel'),
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormDonationExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_description', models.CharField(max_length=500, null=True)),
                ('form_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_extraction', to='forms.presavenewoscformmodel')),
                ('type_of_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_type', to='forms.presavenewoscformdonationextractiontransporttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSaveNewOSCFormAgeGroupMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_people_served_monthly', models.IntegerField(blank=True, null=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_group_mm', to='forms.presavenewoscformagegroup')),
                ('form_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_group_mm', to='forms.presavenewoscformmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='presavenewoscformagegroup',
            name='form_answer',
            field=models.ManyToManyField(related_name='age_group', through='forms.PreSaveNewOSCFormAgeGroupMM', to='forms.presavenewoscformmodel'),
        ),
    ]
