# Generated by Django 4.2.7 on 2025-01-15 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0018_presavenewoscformagegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoscformmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
